### PR TITLE
a few update to the primary fuel docs page

### PR DESCRIPTION
**Pull request by SvenMuller95**

### CODE REVIEW

**Review by JasoonS — APPROVED** [review]
Looks good.

**Review by JasoonS — CHANGES_REQUESTED** [review]
On hold

**Comment by DZakh** [comment]
What do you think about updating the v1 version as well

**Review by JasoonS — APPROVED** [review]

**Comment by JasoonS** [comment]
> What do you think about updating the v1 version as well

We definitely could! Merging this for now.

**Pull request merged**
